export const settlement = [
  "Amstetten",
  "Graz",
  "Innsbruck",
  "Kalsdorf",
  "Klagenfurt",
  "Klosterneuburg",
  "Krems",
  "Leoben",
  "Linz",
  "Mödling",
  "Neusiedl",
  "Oberndorf/Kitzbühel",
  "Pinzgau",
  "Rankweil",
  "Regau",
  "Salzburg",
  "St. Pölten",
  "Völkermarkt",
  "Wien",
  "Wolfurt",
  "Wr. Neustadt",
];
export const client = [
  "Attensam",
  "Attensam Sued",
  "Attensam West",
  "Attensam Nord",
];

export const userRoles = [
  {
    id: 1,
    name: "Time",
    notes: "Timecaption",
  },
  {
    id: 2,
    name: "HrImages",
    notes: "HR Imagecaption",
  },
  {
    id: 3,
    name: "SrControl",
    notes: "SR Control",
  },
  {
    id: 4,
    name: "TWK",
    notes: "Thawn control",
  },
  {
    id: 5,
    name: "Meters",
    notes: "Meters",
  },
  {
    id: 6,
    name: "Vehicles",
    notes: "Module related to all vehicles/car functionalities",
  },
  {
    id: 7,
    name: "SrRoutes",
    notes: "SR Route",
  },
  {
    id: 8,
    name: "NFCTagActivation",
    notes: "Allowing user to activate new tags",
  },
  {
    id: 9,
    name: "TravelTime",
    notes: "Capturing travel time with order nfc tags",
  },
];

export const dummyModules = [
  {
    id: "1",
    name: "Gardenings",
    caption: "GF Erfassung",
    icon: "https://apl.attensam.at/icons/Ic_GF Erfassung@XHDPI.png",
    entity: {
      id: "2",
      name: "Gardenings",
      dataSource: "vw_ase_gardenings",
    },
    workflows: ["1000"],
  },
  {
    id: "2",
    name: "Feedbacks",
    caption: "Rückmeldungen",
    icon: "https://apl.attensam.at/icons/Rückmeldungen_Modul_Icon.png",
    workflows: ["60000"],
  },
  {
    id: "3",
    name: "Objectinfo",
    caption: "Objektinfo",
    icon: "https://apl.attensam.at/icons/Objektinfo_Modul_Icon.png",
    workflows: ["70000"],
  },
  {
    id: "4",
    name: "ToDos",
    caption: "TODOs",
    icon: "https://apl.attensam.at/icons/ToDos_Modul_Icon.png",
    workflows: ["80000"],
  },
  {
    id: "5",
    name: "KostenloseLeistungen",
    caption: "Kostenlose Leistungen",
    icon: "https://apl.attensam.at/icons/KostenloseLeistungen_Modul_Icon.png",
    workflows: ["90000"],
  },
  {
    id: "6",
    name: "MeasurementsGroup",
    caption: "Vermessungen",
    icon: "https://apl.attensam.at/icons/Vermessung_Icon_Medium.png",
    workflows: ["2000"],
  },
  {
    id: "7",
    name: "PreparednessFolders",
    caption: "Bereitschaftsmappen",
    icon: "https://apl.attensam.at/icons/Bereitschaftsmappen_Modul_Icon.png",
    workflows: ["90100"],
  },
  {
    id: "8",
    name: "ServiceReceipts",
    caption: "Mobiler Leistungsschein",
    icon: "https://apl.attensam.at/icons/MobilerLeistungsschein_Modul_Icon.png",
    workflows: ["10000"],
  },
  {
    id: "9",
    name: "Keys",
    caption: "schlüsselverwaltung",
    icon: "https://apl.attensam.at/icons/Schlüsselverwaltung_Modul_Icon.png",
    workflows: [],
  },
  {
    id: "10",
    name: "RatInspection",
    caption: "SB Verplanung",
    icon: "https://apl.attensam.at/icons/SBVerplanung_Modul_Icon.png",
    workflows: [],
  },
  {
    id: "11",
    name: "Containers",
    caption: "Containerverwaltung",
    icon: "https://apl.attensam.at/icons/Containerverwaltung_Modul_Icon.png",
    workflows: [],
  },
  {
    id: "12",
    name: "Sales",
    caption: "Vertriebsapp",
    icon: "https://apl.attensam.at/icons/Vertriebsapp_Modul_Icon.png",
    workflows: [],
  },
  {
    id: "13",
    name: "Controlls",
    caption: "Kontrollgang",
    icon: "https://apl.attensam.at/icons/Kontrollgang_Modul_Icon.png",
    workflows: [],
  },
  {
    id: "14",
    name: "Devices",
    caption: "Geräteverwaltung",
    icon: "https://apl.attensam.at/icons/Geräteverwaltung_Modul_Icon.png",
    workflows: [],
  },
];

//Bookings
export const _dummyData = {
  currentPage: 1,
  pageSize: 25,
  totalEntries: 1058431,
  totalPages: 42338,
  fields: {
    BookingID: {
      isVisible: false,
      name: "BookingID",
      caption: null,
      isFilterable: false,
      isSortable: false,
      type: "Integer",
    },
    ImportState: {
      isVisible: false,
      name: "ImportState",
      caption: "Status",
      isFilterable: true,
      isSortable: true,
      type: "Icon",
      icon: "https://www.dummy-icon-url.com",
    },
    UserId: {
      isVisible: false,
      name: "UserId",
      caption: null,
      isFilterable: false,
      isSortable: false,
      type: "Integer",
    },
    Username: {
      isVisible: true,
      name: "Username",
      caption: "Benutzername",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Personnelnummber: {
      isVisible: true,
      name: "Personnelnummber",
      caption: "Personalnummer",
      isFilterable: true,
      isSortable: true,
      type: "Integer",
    },
    Firstname: {
      isVisible: true,
      name: "Firstname",
      caption: "Vorname",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Lastname: {
      isVisible: true,
      name: "Lastname",
      caption: "Nachname",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Itemnumber: {
      isVisible: true,
      name: "Itemnumber",
      caption: "Datensatznummer",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    BookingType: {
      isVisible: true,
      name: "BookingType",
      caption: "Buchungstyp",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Date: {
      isVisible: true,
      name: "Date",
      caption: "Datum",
      isFilterable: true,
      isSortable: true,
      type: "Date",
    },
    Time: {
      isVisible: true,
      name: "Time",
      caption: "Uhrzeit",
      isFilterable: true,
      isSortable: true,
      type: "Time",
    },
    ItemType: {
      isVisible: true,
      name: "ItemType",
      caption: "Typ",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Street: {
      isVisible: true,
      name: "Street",
      caption: "Straße",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Streetnumber: {
      isVisible: true,
      name: "Streetnumber",
      caption: "Hausnummer",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    ZIP: {
      isVisible: true,
      name: "ZIP",
      caption: "PLZ",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    City: {
      isVisible: true,
      name: "City",
      caption: "Stadt",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Country: {
      isVisible: true,
      name: "Country",
      caption: "Land",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Data1: {
      isVisible: true,
      name: "Data1",
      caption: "Daten 1",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Data2: {
      isVisible: true,
      name: "Data2",
      caption: "Daten 2",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Data3: {
      isVisible: true,
      name: "Data3",
      caption: "Daten 3",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Data4: {
      isVisible: true,
      name: "Data4",
      caption: "Daten 4",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    Data5: {
      isVisible: true,
      name: "Data5",
      caption: "Daten 5",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    FileCounter: {
      isVisible: false,
      name: "FileCounter",
      caption: "FileCounter",
      isFilterable: false,
      isSortable: true,
      type: "Integer",
    },
    Files: {
      isVisible: false,
      name: "Files",
      caption: "Datensatznummer",
      isFilterable: false,
      isSortable: false,
      type: "Array",
    },
  },
  entries: [
    {
      BookingID: 2337448,
      ImportState: "I",
      UserId: 11575,
      Username: "WT0296",
      Personnelnummber: "296",
      Firstname: "Rita Johanna",
      Lastname: "Helminger",
      Itemnumber: "SO70015100",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:57:00",
      ItemType: "Order",
      Street: "Jakobistraße",
      Streetnumber: "15",
      ZIP: "5162",
      City: "Obertrum am See",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337449,
      ImportState: "I",
      UserId: 6594,
      Username: "ATT4305",
      Personnelnummber: "4305",
      Firstname: "Sinisa",
      Lastname: "Manasijev",
      Itemnumber: "ATT111113400",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:57:00",
      ItemType: "Order",
      Street: "Gunoldstraße",
      Streetnumber: "7",
      ZIP: "1190",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337450,
      ImportState: "I",
      UserId: 8952,
      Username: "ATT5349",
      Personnelnummber: "5349",
      Firstname: "Ivica",
      Lastname: "Markovic",
      Itemnumber: "ATT100769900",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:57:00",
      ItemType: "Order",
      Street: "Pötzleinsdorfer Straße",
      Streetnumber: "178-180",
      ZIP: "1180",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337451,
      ImportState: "I",
      UserId: 10646,
      Username: "WT900301",
      Personnelnummber: "900301",
      Firstname: "SUB",
      Lastname: "Magdalena Kalcheva",
      Itemnumber: "SO701077100",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:57:00",
      ItemType: "Order",
      Street: "Pfons-Brenner-H53",
      Streetnumber: "",
      ZIP: "6150",
      City: "Steinach am Brenner",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337444,
      ImportState: "I",
      UserId: 6803,
      Username: "ATT1608",
      Personnelnummber: "1608",
      Firstname: "Ranko",
      Lastname: "Vukovic",
      Itemnumber: "ATT101625200",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:56:00",
      ItemType: "Order",
      Street: "Grundsteingasse",
      Streetnumber: "60",
      ZIP: "1160",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337445,
      ImportState: "I",
      UserId: 10646,
      Username: "WT900301",
      Personnelnummber: "900301",
      Firstname: "SUB",
      Lastname: "Magdalena Kalcheva",
      Itemnumber: "SO701077200",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:56:00",
      ItemType: "Order",
      Street: "Pfons-Brenner-H53",
      Streetnumber: "",
      ZIP: "6150",
      City: "Steinach am Brenner",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337446,
      ImportState: "I",
      UserId: 6816,
      Username: "ATT3886",
      Personnelnummber: "3886",
      Firstname: "Goran",
      Lastname: "Zivanov",
      Itemnumber: "936",
      BookingType: "START",
      Date: "2024-08-22T00:00:00",
      Time: "10:56:00",
      ItemType: "Vehicle",
      Street: "",
      Streetnumber: "",
      ZIP: "",
      City: "",
      Country: "",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337447,
      ImportState: "I",
      UserId: 6587,
      Username: "ATT4127",
      Personnelnummber: "4127",
      Firstname: "Robert",
      Lastname: "Lenard",
      Itemnumber: "ATT100829000",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:56:00",
      ItemType: "Order",
      Street: "Hernalser Hauptstraße",
      Streetnumber: "95",
      ZIP: "1170",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337439,
      ImportState: "D",
      UserId: 6527,
      Username: "ATT2773",
      Personnelnummber: "2773",
      Firstname: "Zoran",
      Lastname: "Jaksic",
      Itemnumber: "ATT12634400",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:55:00",
      ItemType: "Order",
      Street: "Mühlweg",
      Streetnumber: "90",
      ZIP: "1210",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337440,
      ImportState: "D",
      UserId: 11837,
      Username: "SD0992",
      Personnelnummber: "992",
      Firstname: "Giogica",
      Lastname: "Stresna",
      Itemnumber: "S/K102135200",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:55:00",
      ItemType: "Order",
      Street: "Goethestraße",
      Streetnumber: "7",
      ZIP: "8430",
      City: "Leibnitz",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337441,
      ImportState: "D",
      UserId: 6728,
      Username: "ATT1795",
      Personnelnummber: "1795",
      Firstname: "Velibor",
      Lastname: "Savic",
      Itemnumber: "1014",
      BookingType: "START",
      Date: "2024-08-22T00:00:00",
      Time: "10:55:00",
      ItemType: "Vehicle",
      Street: "",
      Streetnumber: "",
      ZIP: "",
      City: "",
      Country: "",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337442,
      ImportState: "I",
      UserId: 6385,
      Username: "ATT3548",
      Personnelnummber: "3548",
      Firstname: "Dejan",
      Lastname: "Avramovic",
      Itemnumber: "917",
      BookingType: "STOP",
      Date: "2024-08-22T00:00:00",
      Time: "10:55:00",
      ItemType: "Vehicle",
      Street: "",
      Streetnumber: "",
      ZIP: "",
      City: "",
      Country: "",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337443,
      ImportState: "I",
      UserId: 6786,
      Username: "ATT4682",
      Personnelnummber: "4682",
      Firstname: "Tibor",
      Lastname: "Urban",
      Itemnumber: "ATT102237700",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:55:00",
      ItemType: "Order",
      Street: "Hernalser Hauptstraße",
      Streetnumber: "148",
      ZIP: "1170",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337429,
      ImportState: "D",
      UserId: 6705,
      Username: "ATT4515",
      Personnelnummber: "4515",
      Firstname: "Marko",
      Lastname: "Radenkovic",
      Itemnumber: "ATT102009200",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Order",
      Street: "Kaiserstraße",
      Streetnumber: "113-115",
      ZIP: "1070",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337430,
      ImportState: "D",
      UserId: 12076,
      Username: "ATT5562",
      Personnelnummber: "5562",
      Firstname: "Aleksandar",
      Lastname: "Todorovic",
      Itemnumber: "ATT13288100",
      BookingType: "BREAK",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Order",
      Street: "Praterstraße",
      Streetnumber: "17",
      ZIP: "1020",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337431,
      ImportState: "D",
      UserId: 6631,
      Username: "ATT3317",
      Personnelnummber: "3317",
      Firstname: "Dragan",
      Lastname: "Mladenovic",
      Itemnumber: "988",
      BookingType: "STOP",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Vehicle",
      Street: "",
      Streetnumber: "",
      ZIP: "",
      City: "",
      Country: "",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337432,
      ImportState: "D",
      UserId: 10025,
      Username: "ATT3050",
      Personnelnummber: "3050",
      Firstname: "Dezsö",
      Lastname: "Mrekva",
      Itemnumber: "W10924918",
      BookingType: "METERSTANDING",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Meter",
      Street: "Siebenbrunnengasse",
      Streetnumber: "61",
      ZIP: "1050",
      City: "Wien",
      Country: "Österreich",
      Data1: "1157",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 1,
      Files: [
        {
          path: "https://pro.attensam.at/files/img_1724316867007.jpg",
          type: "METER",
        },
      ],
    },
    {
      BookingID: 2337433,
      ImportState: "D",
      UserId: 6728,
      Username: "ATT1795",
      Personnelnummber: "1795",
      Firstname: "Velibor",
      Lastname: "Savic",
      Itemnumber: "ATT102272100",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Order",
      Street: "Lindauergasse",
      Streetnumber: "30",
      ZIP: "1160",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337434,
      ImportState: "D",
      UserId: 6343,
      Username: "WT1446",
      Personnelnummber: "1446",
      Firstname: "Gjevat",
      Lastname: "Shabani",
      Itemnumber: "SO10034300",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Order",
      Street: "Auerspergstraße",
      Streetnumber: "15",
      ZIP: "5020",
      City: "Salzburg",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337435,
      ImportState: "D",
      UserId: 6592,
      Username: "ATT1606",
      Personnelnummber: "1606",
      Firstname: "Milan",
      Lastname: "Lukic",
      Itemnumber: "ATT101938900",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Order",
      Street: "Ungargasse",
      Streetnumber: "51",
      ZIP: "1030",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337436,
      ImportState: "D",
      UserId: 12217,
      Username: "ND7021",
      Personnelnummber: "7021",
      Firstname: "Dejan",
      Lastname: "Petrovic",
      Itemnumber: "SO100317400",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Order",
      Street: "Waltherstraße",
      Streetnumber: "2",
      ZIP: "4020",
      City: "Linz",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337437,
      ImportState: "D",
      UserId: 6704,
      Username: "ATT5278",
      Personnelnummber: "5278",
      Firstname: "Igor",
      Lastname: "Prodanov",
      Itemnumber: "909",
      BookingType: "STOP",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Vehicle",
      Street: "",
      Streetnumber: "",
      ZIP: "",
      City: "",
      Country: "",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337438,
      ImportState: "D",
      UserId: 6593,
      Username: "ATT3829",
      Personnelnummber: "3829",
      Firstname: "Dragan",
      Lastname: "Maksimovic",
      Itemnumber: "ATT100370300",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:54:00",
      ItemType: "Order",
      Street: "Seilerstätte",
      Streetnumber: "5",
      ZIP: "1010",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337420,
      ImportState: "D",
      UserId: 6816,
      Username: "ATT3886",
      Personnelnummber: "3886",
      Firstname: "Goran",
      Lastname: "Zivanov",
      Itemnumber: "ATT13362000",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:53:00",
      ItemType: "Order",
      Street: "Erdbergstraße",
      Streetnumber: "112",
      ZIP: "1030",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337421,
      ImportState: "D",
      UserId: 6412,
      Username: "ATT3684",
      Personnelnummber: "3684",
      Firstname: "Ivan",
      Lastname: "Bilic",
      Itemnumber: "ATT100767700",
      BookingType: "OUT",
      Date: "2024-08-22T00:00:00",
      Time: "10:53:00",
      ItemType: "Order",
      Street: "Schikanedergasse",
      Streetnumber: "2",
      ZIP: "1040",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337422,
      ImportState: "D",
      UserId: 10415,
      Username: "ND1005",
      Personnelnummber: "1005",
      Firstname: "Bektas",
      Lastname: "Yalcin",
      Itemnumber: "1467",
      BookingType: "START",
      Date: "2024-08-22T00:00:00",
      Time: "10:53:00",
      ItemType: "Vehicle",
      Street: "",
      Streetnumber: "",
      ZIP: "",
      City: "",
      Country: "",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337423,
      ImportState: "D",
      UserId: 12084,
      Username: "ATT5557",
      Personnelnummber: "5557",
      Firstname: "Adrian Marcin",
      Lastname: "Bochenski",
      Itemnumber: "ATT101998200",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:53:00",
      ItemType: "Order",
      Street: "Kuchelauer Hafenstraße",
      Streetnumber: "98",
      ZIP: "1190",
      City: "Wien",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337424,
      ImportState: "D",
      UserId: 6592,
      Username: "ATT1606",
      Personnelnummber: "1606",
      Firstname: "Milan",
      Lastname: "Lukic",
      Itemnumber: "1035",
      BookingType: "STOP",
      Date: "2024-08-22T00:00:00",
      Time: "10:53:00",
      ItemType: "Vehicle",
      Street: "",
      Streetnumber: "",
      ZIP: "",
      City: "",
      Country: "",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
    {
      BookingID: 2337425,
      ImportState: "D",
      UserId: 11848,
      Username: "WT2481",
      Personnelnummber: "2481",
      Firstname: "Julia",
      Lastname: "Rinderer",
      Itemnumber: "T/V10075000",
      BookingType: "IN",
      Date: "2024-08-22T00:00:00",
      Time: "10:53:00",
      ItemType: "Order",
      Street: "Landstraße",
      Streetnumber: "108 b + c",
      ZIP: "6971",
      City: "Hard",
      Country: "Österreich",
      Data1: "",
      Data2: "",
      Data3: "",
      Data4: "",
      Data5: "",
      Data6: "",
      Data7: "",
      Data8: "",
      Data9: "",
      Data10: "",
      FileCounter: 0,
      Files: [],
    },
  ],
};
export const dummyData = {
  //Items
  currentPage: 1,
  pageSize: 25,
  totalEntries: 1058431,
  totalPages: 42338,
  fields: {
    tagID: {
      isVisible: true,
      name: "tagID",
      caption: "Tag ID",
      isFilterable: false,
      isSortable: false,
      type: "Integer",
    },
    id: {
      isVisible: false,
      name: "id",
      caption: "Status",
      isFilterable: false,
      isSortable: false,
      type: "Icon",
      icon: "https://www.dummy-icon-url.com",
    },
    itemType: {
      isVisible: true,
      name: "itemType",
      caption: "Typ",
      isFilterable: false,
      isSortable: false,
      type: "Integer",
    },
    itemID: {
      isVisible: true,
      name: "itemID",
      caption: "DatensatzID",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    linkedItemID: {
      isVisible: false,
      name: "linkedItemID",
      caption: "Personalnummer",
      isFilterable: false,
      isSortable: false,
      type: "Integer",
    },
    itemNumber: {
      isVisible: true,
      name: "itemNumber",
      caption: "Datensatznummer",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    street: {
      isVisible: true,
      name: "street",
      caption: "Straße",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    streetnumber: {
      isVisible: true,
      name: "streetnumber",
      caption: "Hausnummer",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    zip: {
      isVisible: true,
      name: "zip",
      caption: "PLZ",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    city: {
      isVisible: true,
      name: "city",
      caption: "Stadt",
      isFilterable: true,
      isSortable: true,
      type: "Date",
    },
    country: {
      isVisible: true,
      name: "country",
      caption: "Land",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    data1: {
      isVisible: true,
      name: "data1",
      caption: "Daten 1",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    data2: {
      isVisible: true,
      name: "data2",
      caption: "Daten 2",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    data3: {
      isVisible: true,
      name: "data3",
      caption: "Daten 3",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    data4: {
      isVisible: true,
      name: "data4",
      caption: "Daten 4",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    data5: {
      isVisible: true,
      name: "data5",
      caption: "Daten 5",
      isFilterable: true,
      isSortable: true,
      type: "String",
    },
    FileCounter: {
      isVisible: false,
      name: "FileCounter",
      caption: "FileCounter",
      isFilterable: false,
      isSortable: true,
      type: "Integer",
    },
    Files: {
      isVisible: false,
      name: "Files",
      caption: "Datensatznummer",
      isFilterable: false,
      isSortable: false,
      type: "Array",
    },
  },
  entries: [
    {
      tagID: "",
      id: 428160,
      itemType: "Order",
      itemID: "N7L861P30QZ32G7L6X230YGLS",
      linkedItemID: "",
      itemNumber: "ATT915072000",
      street: "Mariahilfer Straße",
      streetnumber: "89a",
      zip: "1060",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "RG",
      data3: "Entsorgung von Gerümpel",
      data4: "1008771",
      data5: "Realkanzlei Edlauer",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T15:13:10",
      modifiedDate: "2024-08-22T15:19:08.4265384",
    },
    {
      tagID: "",
      id: 428161,
      itemType: "Order",
      itemID: "N7L82GZO0K7N9G7L6X230YGLS",
      linkedItemID: "",
      itemNumber: "ATT915071800",
      street: "Rauhensteingasse",
      streetnumber: "10",
      zip: "1010",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "RG",
      data3: "Entsorgung von Gerümpel",
      data4: "1061411",
      data5: "W. Rest Realitäten GmbH",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T15:13:10",
      modifiedDate: "2024-08-22T15:19:08.7396548",
    },
    {
      tagID: "",
      id: 428159,
      itemType: "Order",
      itemID: "N7L7QOAH00G9YG7L5MO00YGLS",
      linkedItemID: "",
      itemNumber: "ATT805681700",
      street: "Anton-Scharff-Gasse",
      streetnumber: "4",
      zip: "1120",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "SR",
      data3: "Winterservice",
      data4: "1020060",
      data5: "IMV Immobilien Management GmbH",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T14:49:10",
      modifiedDate: "2024-08-22T15:19:08.5537415",
    },
    {
      tagID: "",
      id: 428158,
      itemType: "Order",
      itemID: "N7L7GY3V0GK7HG7L367H0YGLS",
      linkedItemID: "",
      itemNumber: "ATT102394000",
      street: "Ruzickagasse",
      streetnumber: "88-104",
      zip: "1230",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "AF",
      data3: "Aussenflächenkehrung",
      data4: "1001191",
      data5: "Mersich Immobilien GmbH",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T14:37:09",
      modifiedDate: "2024-08-22T15:19:08.719488",
    },
    {
      tagID: "",
      id: 428156,
      itemType: "Order",
      itemID: "N7L7FN400DO2CG7L5R0C0YGLS",
      linkedItemID: "",
      itemNumber: "ATT102393900",
      street: "Zachgasse",
      streetnumber: "6",
      zip: "1220",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "HR",
      data3: "Hausbetreuung inkl. Bewässerung",
      data4: "1003395",
      data5: "WIEN-SÜD - Gemeinn. Bau- und Wohnungs-",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T14:31:11",
      modifiedDate: "2024-08-22T15:19:08.3998862",
    },
    {
      tagID: "",
      id: 428157,
      itemType: "Order",
      itemID: "N7L7EDWQ0HIQCG7L6X230YGLS",
      linkedItemID: "",
      itemNumber: "ATT915071400",
      street: "Neulinggasse",
      streetnumber: "22",
      zip: "1030",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "RG",
      data3: "Entsorgung von Gerümpel",
      data4: "1002462",
      data5: "Pensionsversicherungsanstalt",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T14:31:11",
      modifiedDate: "2024-08-22T15:19:08.6921225",
    },
    {
      tagID: "",
      id: 428154,
      itemType: "Order",
      itemID: "N7L7KI0M03F3WG7L4AFB0YGLS",
      linkedItemID: "",
      itemNumber: "STP915070300",
      street: "Holzleiten",
      streetnumber: "14",
      zip: "3350",
      city: "Haag",
      country: "Österreich",
      data1: "Attensam Nord",
      data2: "GR",
      data3:
        "Abrufbestellung IP3/4900643130 Heckenschnitt und Unkrautbekämpfung RV550/4600026845",
      data4: "1034604",
      data5: "ÖBB Immobilienmanagement GmbH",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T13:43:10",
      modifiedDate: "2024-08-22T14:49:10.1030468",
    },
    {
      tagID: "",
      id: 428155,
      itemType: "Order",
      itemID: "N7L7MVPS03IORG7L51FF0YGLS",
      linkedItemID: "",
      itemNumber: "ATT915070500",
      street: "Goldschlagstraße",
      streetnumber: "123",
      zip: "1150",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "RG",
      data3: "Entsorgung von Gerümpel ",
      data4: "1000965",
      data5: "Atico Immobilien Gesellschaft m.b.H.",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T13:43:10",
      modifiedDate: "2024-08-22T14:37:09.1905002",
    },
    {
      tagID: "",
      id: 428153,
      itemType: "Order",
      itemID: "M8I76MT60XB4HF8I41JJYGLST",
      linkedItemID: "",
      itemNumber: "ATT804769000",
      street: "Passauer Gasse",
      streetnumber: "29",
      zip: "3400",
      city: "Klosterneuburg",
      country: "Österreich",
      data1: "Attensam",
      data2: "SR",
      data3: "Winterservice",
      data4: "1059581",
      data5: "Katrin Hammerschmidt",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T13:31:09",
      modifiedDate: "2024-08-22T14:37:08.7547481",
    },
    {
      tagID: "",
      id: 428152,
      itemType: "Order",
      itemID: "N7L7CMCI09O08G7L441N0YGLS",
      linkedItemID: "",
      itemNumber: "S/K915070000",
      street: "Lehargasse",
      streetnumber: "4/1-2",
      zip: "7400",
      city: "Oberwart / Felsoor",
      country: "Österreich",
      data1: "Attensam Sued",
      data2: "GR",
      data3: " Baumschnitt im Innenhof sowie hinter Lokal, Obj. 8064",
      data4: "1076598",
      data5: "Oberwarter gemeinnützige Bau-, Wohn- und Siedlungsgenossenschaft",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T13:25:10",
      modifiedDate: "2024-08-22T14:25:06.8025795",
    },
    {
      tagID: "",
      id: 428151,
      itemType: "Order",
      itemID: "N7L7767800INAG7L441N0YGLS",
      linkedItemID: "",
      itemNumber: "S/K915069500",
      street: "Hannersdorf",
      streetnumber: "241, 242",
      zip: "7473",
      city: "Hannersdorf",
      country: "Österreich",
      data1: "Attensam Sued",
      data2: "GR",
      data3: "Hecken und Strauchschnitt, Obj. 8216",
      data4: "1076598",
      data5: "Oberwarter gemeinnützige Bau-, Wohn- und Siedlungsgenossenschaft",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T13:19:07",
      modifiedDate: "2024-08-22T14:13:06.0427383",
    },
    {
      tagID: "",
      id: 428150,
      itemType: "Order",
      itemID: "N7L70I780URO0G7L6X230YGLS",
      linkedItemID: "",
      itemNumber: "ATT915069400",
      street: "Bürgerspitalgasse",
      streetnumber: "13",
      zip: "1060",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "RG",
      data3: "ekelerregende Substanzen",
      data4: "1000104",
      data5: "I.V.T. Immobilien-, Treuhand-",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T13:07:11",
      modifiedDate: "2024-08-22T15:07:07.0877354",
    },
    {
      tagID: "",
      id: 428149,
      itemType: "Order",
      itemID: "N7L6UAPY0QQA9G7L51FF0YGLS",
      linkedItemID: "",
      itemNumber: "ATT915069200",
      street: "Dammstraße",
      streetnumber: "38",
      zip: "1200",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "RG",
      data3: "einmalige Bodengrundreinigung inkl. Entsorgung von Gerümpel ",
      data4: "1024105",
      data5: "Immobilienkanzlei Schneeweiss",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T12:55:08",
      modifiedDate: "2024-08-22T13:49:08.6724488",
    },
    {
      tagID: "",
      id: 428147,
      itemType: "Order",
      itemID: "N7L6E0N60MG2IG7L43UL0YGLS",
      linkedItemID: "",
      itemNumber: "S/K701171900",
      street: "Wiener Straße",
      streetnumber: "56-58",
      zip: "8605",
      city: "Kapfenberg",
      country: "Österreich",
      data1: "Attensam Sued",
      data2: "UR",
      data3: "Büroreinigung",
      data4: "1080988",
      data5: "DKOB GmbH & Co. KG",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T12:31:07",
      modifiedDate: "2024-08-22T13:25:09.3499171",
    },
    {
      tagID: "",
      id: 428148,
      itemType: "Order",
      itemID: "N7L6FWR20X9MDG7L441N0YGLS",
      linkedItemID: "",
      itemNumber: "S/K805681600",
      street: "Eichberg",
      streetnumber: "20",
      zip: "2640",
      city: "Gloggnitz",
      country: "Österreich",
      data1: "Attensam Sued",
      data2: "SR",
      data3: "Winterservice",
      data4: "1008240",
      data5: "Schwarzataler Immobilien ",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T12:31:07",
      modifiedDate: "2024-08-22T13:25:09.3695232",
    },
    {
      tagID: "",
      id: 428146,
      itemType: "Order",
      itemID: "N7L6AVGV0E0UCG7L43UL0YGLS",
      linkedItemID: "",
      itemNumber: "S/K805681500",
      street: "Kasernstraße",
      streetnumber: "2a",
      zip: "8101",
      city: "Kirchenviertel",
      country: "Österreich",
      data1: "Attensam Sued",
      data2: "SR",
      data3: "Winterservice Garagenanlage",
      data4: "1080970",
      data5: "FIVSEN GmbH",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T12:25:09",
      modifiedDate: "2024-08-22T13:19:06.2858976",
    },
    {
      tagID: "",
      id: 428145,
      itemType: "Order",
      itemID: "N7L60MXU0TPARG7L43UL0YGLS",
      linkedItemID: "",
      itemNumber: "S/K201944200",
      street: "Gewerbering",
      streetnumber: "6",
      zip: "8077",
      city: "Gössendorf",
      country: "Österreich",
      data1: "Attensam Sued",
      data2: "GF",
      data3: "Grünflächenbetreuung",
      data4: "1080749",
      data5: "Hannes Herbst Immobilientreuhand ",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T12:13:11",
      modifiedDate: "2024-08-22T13:07:10.8060493",
    },
    {
      tagID: "",
      id: 428143,
      itemType: "Order",
      itemID: "N7L60S1W0HQHFG7L43UL0YGLS",
      linkedItemID: "",
      itemNumber: "S/K805681400",
      street: "Gewerbering",
      streetnumber: "6",
      zip: "8077",
      city: "Gössendorf",
      country: "Österreich",
      data1: "Attensam Sued",
      data2: "SR",
      data3: "Winterservice",
      data4: "1080749",
      data5: "Hannes Herbst Immobilientreuhand ",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T12:07:07",
      modifiedDate: "2024-08-22T13:01:07.8032069",
    },
    {
      tagID: "",
      id: 428144,
      itemType: "Order",
      itemID: "N7L620LS0AJKFG7L51FF0YGLS",
      linkedItemID: "",
      itemNumber: "ATT915068800",
      street: "Piaristengasse",
      streetnumber: "29",
      zip: "1080",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "RG",
      data3: "Entsorgung von Gerümpel ",
      data4: "1000151",
      data5: "Öster. Siedlungsw. Gem. Wohnungs AG",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T12:07:07",
      modifiedDate: "2024-08-22T13:01:07.8214963",
    },
    {
      tagID: "",
      id: 428142,
      itemType: "Order",
      itemID: "N7L60Q370AK5KG7L43UL0YGLS",
      linkedItemID: "",
      itemNumber: "S/K915068700",
      street: "Gewerbering",
      streetnumber: "6",
      zip: "8077",
      city: "Gössendorf",
      country: "Österreich",
      data1: "Attensam Sued",
      data2: "GR",
      data3: "Aufbereitung, Schmalspur und A1 der GF",
      data4: "1080749",
      data5: "Hannes Herbst Immobilientreuhand ",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T12:07:06",
      modifiedDate: "2024-08-22T13:01:07.4113559",
    },
    {
      tagID: "",
      id: 428141,
      itemType: "Order",
      itemID: "N7L6P7JV029F9G7L47P30YGLS",
      linkedItemID: "",
      itemNumber: "ATT805681300",
      street: "Klammergasse",
      streetnumber: "3",
      zip: "1090",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "SR",
      data3: "Winterservice",
      data4: "1031997",
      data5: "RA, Mag. Florian Masser",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T11:49:11",
      modifiedDate: "2024-08-22T12:43:09.9348235",
    },
    {
      tagID: "",
      id: 428139,
      itemType: "Order",
      itemID: "N7L6HDIQ0SBMYG7L3F3U0YGLS",
      linkedItemID: "",
      itemNumber: "SO915067900",
      street: "Pass Thurn",
      streetnumber: "29",
      zip: "5730",
      city: "Mittersill",
      country: "Österreich",
      data1: "Attensam West",
      data2: "GR",
      data3: "Grünflächenregie",
      data4: "1054239",
      data5: "Dr. Gottfried Breuninger",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T11:37:07",
      modifiedDate: "2024-08-22T11:43:07.4020602",
    },
    {
      tagID: "",
      id: 428140,
      itemType: "Order",
      itemID: "N7L6JGAR0H6YPG7L3F3U0YGLS",
      linkedItemID: "",
      itemNumber: "SO915068000",
      street: "Paßthurn",
      streetnumber: "28",
      zip: "5730",
      city: "Paßthurn",
      country: "Österreich",
      data1: "Attensam West",
      data2: "GR",
      data3: "Grünflächenregie",
      data4: "1075354",
      data5: "Greenventions GmbH",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T11:37:07",
      modifiedDate: "2024-08-22T11:37:07.2808398",
    },
    {
      tagID: "",
      id: 428138,
      itemType: "Order",
      itemID: "N7L6G4AT0LH6KG7L3F3U0YGLS",
      linkedItemID: "",
      itemNumber: "SO915067800",
      street: "Pass Thurn ",
      streetnumber: "26 - 31",
      zip: "5730",
      city: "Mittersill",
      country: "Österreich",
      data1: "Attensam West",
      data2: "GR",
      data3: "Grünflächenregie",
      data4: "1046507",
      data5: "Verwaltungsgenossenschaft ",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T11:31:08",
      modifiedDate: "2024-08-22T11:37:06.8516828",
    },
    {
      tagID: "",
      id: 428135,
      itemType: "Order",
      itemID: "N7L6APIA0UAI3G7L3YL90YGLS",
      linkedItemID: "",
      itemNumber: "ATT102393700",
      street: "Klammergasse",
      streetnumber: "3",
      zip: "1090",
      city: "Wien",
      country: "Österreich",
      data1: "Attensam",
      data2: "HR",
      data3: "Hausbetreuung",
      data4: "1031997",
      data5: "RA, Mag. Florian Masser",
      data6: null,
      data7: null,
      data8: null,
      data9: null,
      data10: null,
      createdBy: "ATINA_SYNC",
      createdDate: "2024-08-22T11:25:10",
      modifiedDate: "2024-08-22T12:43:09.9049167",
    },
  ],
};
