import Head from "next/head";
import { Inter } from "next/font/google";
import { getSession } from "next-auth/react";
import styles from "@/components/dashboard/dashboard-card.module.css";
import { useSelector } from "react-redux";
import Card from "@/components/dashboard/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data } = useSelector((state) => state.attensam);
  return (
    <>
      <Head>
        <title>Attensam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.gridContainer}>
          {/* {data.map((module, index) => (
            <Card key={index} cardInfo={module} />
          ))} */}
        </div>
      </div>
    </>
  );
}
export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }
  return {
    props: { session },
  };
};
